# Site settings
title: Chad's Starter site
email: chad.powers@kaazing.com
description: > # this means to ignore newlines until "baseurl:"
  In this first version, I am trying to have several different blog posts
  that contain links to each other
baseurl: "/test" # the subpath of your site, e.g. /blog/
url: "http://chadpowers.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  chadpowers

# Build settings
markdown: kramdown
